name: Tracee-eBPF Dup Detection

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download Tracee-eBPF Release
      run: |
        wget https://github.com/aquasecurity/tracee/releases/download/v0.19.0/tracee-x86_64.v0.19.0.tar.gz
        tar -xzvf tracee-x86_64.v0.19.0.tar.gz
        echo "finished extraction"
        pwd
        ls -al

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libelf-dev libpcap-dev

    - name: Run Tracee in background
      run: |
        sudo ./dist/tracee-ebpf -f e=dup* -o format:gob -o out-file:/tmp/tracee.gob &
        echo "Tracee PID: $!"
      id: tracee

    - name: Install Python and run script
      run: |
        sudo apt-get install -y python3
        python3 -c 'import os; fd = os.dup(1); print(f"dup(1) succeeded, fd = {fd}")'

    - name: Check Tracee output for dup syscall
      run: |
        # Wait a bit for Tracee to catch up
        ls -al /tmp/tr*
        sleep 5
        cat /tmp/tracee.gob
        # This is a conceptual command; actual implementation may vary
        if grep -q "dup(" /tmp/tracee.gob; then
          echo "dup syscall detected successfully."
          exit 0
        else
          echo "dup syscall not detected."
          exit 1
        fi
